services:
#    sandy.example:
#        class: SandyBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  my.listener:
    class: SandyBundle\EventListener\ProductModificationListener
    arguments:
      - '@swiftmailer.mailer'
    tags:
      - { name: kernel.event_listener, event: akeneo.storage.post_save, method: onPostSave }

